spring.datasource.url=jdbc:mysql://localhost:3306/redSocial
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

spring.application.name=API red social android
firebase.credentials.path=notificacionespush-859a4-firebase-adminsdk-fbsvc-224c055985.json
gcs.bucket.name=laravel-test-yohalmo
gcs.credentials.path=classpath:google-cloud-storage.json

